name: webapp
on:
  push:
    branches:
      - main
jobs:
  build:
    name: "build webapp"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@main

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          context: .
          push: true
          username: d3vpasha
          password: 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
          registry: ghcr.io