name: webapp
on:
  push:
    branches:
      - main
jobs:
  build:
    name: "build webapp"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@main

      - name: Login to Github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: d3vpasha
          password: ${{ secrets.CR_PAT }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          context: .
          push: true